name: "Branch build"
on:
  push:
    branches-ignore:
      - main
      - develop
      - release/*
jobs:
  install-notest:
    if: "github.repository != 'WebGoat/WebGoat'"
    runs-on: ubuntu-latest
    name: "Package and linting"
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ubuntu-latest-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-latest-m2
      - name: Test with Maven
        run: mvn install -DskipTests
      - name: SAST
        uses: Contrast-Security-OSS/contrastscan-action@initial
        with:
          artifact: webgoat-server/target/webgoat-server-8.2.3-SNAPSHOT.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTRAST__API__USER_NAME: ${{ secrets.CONTRAST_USERNAME }}
          CONTRAST__API__SERVICE_KEY: ${{ secrets.CONTRAST_SERVICE_KEY }}
          CONTRAST__API__API_KEY: ${{ secrets.CONTRAST_API_KEY }}
          CONTRAST__API__ORGANIZATION_ID: ${{ secrets.CONTRAST_ORG_ID }}

  testing:
    if: "github.repository != 'WebGoat/WebGoat'"
    needs: install-notest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - mvn -pl '!webgoat-integration-tests' test
          - mvn -pl webgoat-integration-tests test
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ubuntu-latest-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-latest-m2
      - name: Test with Maven
        run: ${{ matrix.args }}
